#!/usr/bin/env bash

rm -f ~/.kube/config
if [ ! -s ~/.kube/config ] ; then
  scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ConnectTimeout=3 -o LogLevel=quiet runner:.kube/config ~/.kube/ > /dev/null 2>&1 \
  && chmod 600 ~/.kube/config
fi
if [ ! -s ~/.kube/config ] ; then
  echo "Can not get KUBECONFIG file, Kubernetes is not ready yet ?" >&2
  exit 1
else
  exec /usr/local/bin/kubectl-bin "$@"
fi
